name: Flutter Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: |
        cd emoji_invaders
        flutter pub get
    
    - name: Verify formatting
      run: |
        cd emoji_invaders
        dart format --set-exit-if-changed lib/ test/
    
    - name: Analyze project source
      run: |
        cd emoji_invaders
        flutter analyze
    
    - name: Run tests
      run: |
        cd emoji_invaders
        flutter test --coverage
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: emoji_invaders/coverage/lcov.info
        fail_ci_if_error: true
